### PR TITLE
add docs for F# HTML

### PR DESCRIPTION
**Pull request by ChrisNikkel**

### CODE REVIEW

**Comment by jonsequitur** [comment]
The CI failure can be resolved by rebasing onto the latest commits from master.

**Comment by ChrisNikkel** [comment]
It appears something has changed to make this not work in F# any longer:
```fsharp
display(HtmlString("<b style=\"color:blue\">Hello!</b>"))
```
```
Unhandled Exception
Unable to cast object of type 'Microsoft.AspNetCore.Html.HtmlString' to type 'Microsoft.DotNet.Interactive.Rendering.PocketView'.
   at Microsoft.DotNet.Interactive.Rendering.TypeFormatter`1.Microsoft.DotNet.Interactive.Rendering.ITypeFormatter.Format(Object instance, TextWriter writer)
   at Microsoft.DotNet.Interactive.Rendering.Formatter`1.FormatTo(T obj, TextWriter writer, String mimeType)
   at Microsoft.DotNet.Interactive.Rendering.Formatter.FormatTo[T](T obj, TextWriter writer, String mimeType)
   at Microsoft.DotNet.Interactive.Rendering.Formatter.ToDisplayString(Object obj, String mimeType)
   at Microsoft.DotNet.Interactive.Kernel.display(Object value, String mimeType)
   at <StartupCode$FSI_0005>.$FSI_0005.main@()```

This shouldn't be merged until this issue is addressed.

**Comment by jonsequitur** [comment]
This bug was fixed: https://github.com/dotnet/try/issues/639.

**Comment by ChrisNikkel** [comment]
I think this will remain broken for many until there is a new nuget package released. 
 It appears `https://www.nuget.org/packages/dotnet-try/` was last updated 12 days ago.

**Pull request merged**
