### PR TITLE
Add nuget.config to the .gitignore

### PR DESCRIPTION
**Pull request by BillWagner**
We probably want more here, but I wanted to add this entry as I upgraded.

### CODE REVIEW

**Comment by jonsequitur** [comment]
@BillWagner, just a heads-up, we'll be moving the Try .NET source code into this repo at some point and the current contents will be restructured at that time. There will be a NuGet.config folder in the root.

**Comment by BillWagner** [comment]
@jonsequitur  That makes sense.

I just noticed that we'd mistakenly checked in a number of build artifacts

See [Beginners](https://github.com/dotnet/try/tree/master/Samples/Beginners/myapp) and [ExploreCSharp8](https://github.com/dotnet/try/tree/master/Samples/csharp8/ExploreCsharpEight)

Do you want me to add that task to this PR, or make a separate one?

**Comment by jonsequitur** [comment]
Either way is fine.

**Comment by BillWagner** [comment]
@jonsequitur 

I updated this PR:
- remove the files that should have been ignored
- updated the .gitignore to the github recommend Visual Studio version, and include the nuget.config file as well

**Pull request merged**
